Convert mouse clicks to driver calls
iis-powp-2020z/powp_jobs2d_projects pull request #3
Opened 2021-01-21 17:21 UTC by tobiashiro

2021-01-21 18:57 UTC, kowallus requested changes
Some modifications are necessary.

2021-01-21 18:57 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/TestJobs2dApp.java
> +	private static JPanel jPanel;
This field is unnecessary.

2021-01-21 18:57 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/features/DrawerPanelClickMouseListenerFeature.java
> +        startX = mouseEvent.getX()-268;
An unextracted constant. The value could be calculated instead of fixed.

2021-01-21 18:57 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/features/DrawerPanelClickMouseListenerFeature.java
> +public class DrawerPanelClickMouseListenerFeature implements MouseListener, Job2dDriver {
This class shouldn't be a driver, since it is not (and do not need to be) used as a driver.

2021-01-21 18:57 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/features/DrawerPanelClickMouseListenerFeature.java
> +        setPosition(startX, startY);
The goal is to call a current app driver (manager.getCurrentDriver), not draw directly.

2021-01-28 13:06 UTC, kowallus requested changes
Not correct. Try to revise current and previous comments.

2021-01-28 13:06 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/features/DrawerPanelClickMouseListenerFeature.java
> +        driverManager.getCurrentDriver();
This line does nothing!

2021-01-28 13:06 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/features/DrawerPanelClickMouseListenerFeature.java
> +    private DrawPanelController drawController;
You shouldn't use drawPanelController directly at all. Remove

2021-01-28 13:06 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/features/DrawerPanelClickMouseListenerFeature.java
> +    }
This is "dead end". Remove this code to find correct solution.

2021-01-30 12:48 UTC, kowallus requested changes
Minor issue

2021-01-30 12:48 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/features/DrawerPanelClickMouseListenerFeature.java
>          startX = mouseEvent.getX() - (application.getFreePanel().getSize().width/2);
Unnecessary coupling to Application. It should be enough to keep freePanel reference.

2021-01-30 12:48 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/features/DrawerPanelClickMouseListenerFeature.java
>          if(isClicked){
Maybe you can check if it is left or right click?

2021-01-30 13:09 UTC, kowallus commented
Fix conflicts! Merge changes from main repo.

2021-01-30 13:35 UTC, Jakubszadkowski approved these changes

2021-01-30 13:54 UTC, merged